import com.MajorException;

public class CheckedTest3 {
	public static void main(String[] args) throws Exception {
		throw new MajorException("An error occured.");
	}
}
