import com.MajorException;

public class CheckedTest4 {
	public static void main(String[] args){
		throw new MajorException("An error occured.");
	}
}
